a=float(input('Enter the first number:'))
b=float(input('Enter the second number:'))
print('\n')
sum =float(a+b)
print('addition:',sum)
sub=float(a-b)
print('subtraction:',sub)
mul=float(a*b)
print('multiplication:',mul)
div=float(a/b)
print('division:',div)